### ISSUE TITLE
[Django 5] Static 

### ISSUE THREAD

**Issue by ynschoi** [ynschoi/ynschoi.github.io#17]
_[Source: 2022년 멋쟁이사자처럼 직장인 온앤오프 강의, 강사: Heeham]_

# Django Static 
- Django에서는 Template과 Static을 활용해서, 스타일링을 겸비한 HTML Webpage를 만들 수 있음 
  - **Template**은 dynamic으로, 어떤 데이터가 채워지는지에 따라 달라짐
  - **Static**은 CSS, 이미지, Javascript 등으로 서비스의 이용자가 바뀌어도 항상 동일하게 제공되어야 하는 파일에 해당 

<img src="https://user-images.githubusercontent.com/97776406/153749760-212756ea-5d6d-4c10-b385-bb05f03a94c3.svg" width="40%" height="40%"/>

### 1.1. Static Namespacing (디렉토리 구조)
1) 앱 디렉토리(```ex. posts/```) 내에, ```static/``` 디렉토리를 만들고 
2) ```static``` 디렉토리 내에 앱 이름과 동일한 디렉토리(```ex. posts/```)를 다시 만들어 줌 **(= Namespacing)**
3) 해당 디렉토리 ```ex. posts/static/posts``` 내에 static 파일 넣기
   1) css 파일 생성(```ex. style.css```)
   2) image 파일은 별도의 ```images/``` 디렉토리를 만들어 넣어주기
- Static도 Template과 마찬가지로 **Namespacing**을 이용하여, 각 앱 단위로 구분하여 관리   
  - 단, Static은 개발단계에서만 앱 단위로 관리하며, 서비스 런칭 후에는 하나로 합쳐서 사용 _(왜? 어떻게? 는 나중에 다룸)_  
### 1.2. Template에서 Static 사용하기: Static Tag 이용 
- **Template**(```ex. index.html```)에서 **Static**인 CSS(```ex. style.css```) 또는 이미지(```ex. cats.jpg```) 사용하기
  - Template에서 Static을 불러오기 위해서 **```{% load static %}```** 태그를 작성
  - Static 파일의 경로는 **```{% static '경로' %}```** 형태로 작성 
    - _ex. ```{% static 'posts/style.css' %}``` or ```{% static 'posts/images/cats.jpg' %}```_
  - 위의 작성방식은 Django Template Language에 해당하므로, Template에서만 활용 가능
 
```[템플릿] posts/templates/posts/index.html```
```html
{% load static %}    # <-- (1)

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'posts/style.css' %}">    # <-- (2)
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>youngsugram</title>
</head>
<body>
    <h1>Posts</h1>
    <img id="profile"  src="{% static 'posts/images/cats.jpg' %}" alt="cat">    # <-- (3)
</body>

#의미
#(1) Template에서 Static을 불러오기 위한 태그
#(2) Static인 css를 참조할 때, {% static '경로' %} 활용
#(3) Static인 이미지를 참조할 때, {% static '경로' %} 활용
```
```[Static: CSS] posts/static/posts/style.css```
```css
h1{
    color: red;
}

#profile{
    width: 400px;
}
```
### 1.3. Static에서 Static 사용하기: 상대경로 이용 
- Static인 CSS(```ex. style.css```)에서 Static인 이미지(```ex. cats.jpg```) 사용해야 하는 경우 (ex. background-image)
  - Django Template Language 기반의 static 태그 ```{% static '경로' %}``` 사용 불가 
  - 단, 절대 경로로 하드코딩하는 경우 아래와 같은 문제 때문에 경로 인식이 어려움
    - 개발하는 환경과 서비스를 배포할 때의 환경이 달라짐
    - 서비스 배포 과정에서 static 디렉토리를 하나로 합치는 과정에서 경로가 달라짐 
  - 따라서 static에서 static 사용하는 경우, namespacing을 기반으로 한 상대경로 이용하여 경로 작성
    - 추후 static이 합쳐지는 경우에도 namespacing 해둔 경로는 영향을 받지 않기 때문에 문제 없음 

```[템플릿] posts/templates/posts/index.html```
```html
{% load static %}   

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'posts/style.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>youngsugram</title>
</head>
<body>
    <h1>Posts</h1>
    <div class="profile_bg"></div>    # <-- (1)
    <img id="profile"  src="{% static 'posts/images/cats.jpg' %}" alt="cat">
</body>

#의미
#(1) profile_bg이라는 class의 div
```
```[Static: CSS] posts/static/posts/style.css```
```css
.profile_bg{    # <-- (1)
    background-image: url(images/cats.jpg);    # <-- (2)
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center;
    width: 400px;
    height: 400px;
}

#의미
#(1) profile_bg이라는 class에 대하여 styling
#(2) div의 styling 시 background 이미지로 static 이미지 파일 활용 - 상대경로 base 
```
